version: '3'
services:
  elso:
    build: .
    ports: ["8080:8080"]
    volumes:
      - ./data:/app/data
    command: ["./healthchain", "--algorithm", "elso"]

  basic:
    build: .
    ports: ["8081:8080"]
    command: ["./healthchain", "--algorithm", "basic"]

  offchain:
    build: .
    ports: ["8082:8080"]
    command: ["./healthchain", "--algorithm", "offchain"]